apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: sktst
  labels:
    app: sk-tst
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
